[workspace]

members = [
    "crates/threebug-core",
    "crates/threebug-server",
    "crates/threebug-client",
]


[patch."https://github.com/rezural/bevy_spicy_networking"]
bevy_spicy_networking = { path = "vendor/bevy_spicy_networking" }

